language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
sudo: true

services:
  - docker

install:
  - pip install cookiecutter invoke

script:
  - invoke test
